### ISSUE TITLE
ATT&CK to Excel exporter chokes on early versions (1.0 to 4.0)

### ISSUE THREAD

**Issue by mvglasow** [mitre-attack/attack-scripts#55]
### To reproduce:

`python3 attackToExcel.py -output ~/Documents/attack -version v1.0`

### Expected result:

A set of XLS files with the data for V1.0

### Actual result:

Conversion fails with an error and no output is produced.
```
Traceback (most recent call last):
  File "attackToExcel.py", line 175, in <module>
    main(args.domain, args.version, args.output)
  File "attackToExcel.py", line 151, in main
    dataframes = build_dataframes(get_data_from_version(domain, version), domain)
  File "attackToExcel.py", line 33, in build_dataframes
    "tactics": stixToDf.tacticsToDf(src, domain),
  File "/home/vonglasowm/src/attack-scripts/attackToExcel/stixToDf.py", line 166, in tacticsToDf
    "tactics": pd.DataFrame(tactic_rows).sort_values("name"),
  File "/home/vonglasowm/src/attack-scripts/env/lib/python3.6/site-packages/pandas/core/frame.py", line 5291, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "/home/vonglasowm/src/attack-scripts/env/lib/python3.6/site-packages/pandas/core/generic.py", line 1560, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'name'
```

### Versions used:

6347904c on Ubuntu 18.04

### Additional information:

Exporting the latest version (without specifying a `--version` argument) works as expected as of today. `V2.0` gives an error which looks like the above, `V3.0` and `V4.0` also error out, but with somewhat different messages. `V5.0`, `V6.0`, `V7.0` and `V8.0` complete without errors.

**Comment by isaisabel** [comment]
Hi @mvglasow,

As noted in #57, the ATT&CK data model has changed substantially over the last few years. Scripts on this repo generally support the last few versions, but if you go too far back they will start to act up.

It's also worth noting that attackToExcel is still a work in progress and the format and functionality may change before the full release. #57 covers the need to better document the fact that scripts won't work on older versions of ATT&CK, so I'm closing this issue.
